// TOEIC 800~900점대 필수 어휘
const WORDS = [
  { id: 1, en: 'accommodate', ko: '수용하다, 편의를 봐주다', level: '800', example: 'The hotel can accommodate up to 300 guests.' },
  { id: 2, en: 'acquire', ko: '습득하다, 인수하다', level: '800', example: 'The company acquired a smaller competitor last year.' },
  { id: 3, en: 'allocate', ko: '할당하다', level: '800', example: 'Funds have been allocated to the marketing department.' },
  { id: 4, en: 'anticipate', ko: '예상하다', level: '800', example: 'We anticipate strong sales during the holiday season.' },
  { id: 5, en: 'appraisal', ko: '(성과) 평가', level: '900', example: 'Employees receive a performance appraisal every year.' },
  { id: 6, en: 'approximately', ko: '대략', level: '800', example: 'The project will take approximately six months to complete.' },
  { id: 7, en: 'arrangement', ko: '준비, 마련', level: '800', example: "Please make arrangements for the client's visit." },
  { id: 8, en: 'assess', ko: '평가하다', level: '800', example: 'Managers assess employee performance quarterly.' },
  { id: 9, en: 'attain', ko: '달성하다', level: '800', example: 'The team attained its sales target ahead of schedule.' },
  { id: 10, en: 'attentive', ko: '세심한, 주의를 기울이는', level: '900', example: "The staff were attentive to every customer's needs." },
  { id: 11, en: 'authorize', ko: '승인하다', level: '800', example: 'Only the manager can authorize this expense.' },
  { id: 12, en: 'beneficial', ko: '이로운', level: '800', example: 'Regular training is beneficial for new employees.' },
  { id: 13, en: 'budget', ko: '예산', level: '800', example: 'The department stayed within its annual budget.' },
  { id: 14, en: 'candidate', ko: '후보자, 지원자', level: '800', example: 'Three candidates were shortlisted for the position.' },
  { id: 15, en: 'collaborate', ko: '협력하다', level: '800', example: 'Our team collaborates closely with the design department.' },
  { id: 16, en: 'commence', ko: '시작되다', level: '800', example: 'The construction project will commence next month.' },
  { id: 17, en: 'compensate', ko: '보상하다', level: '800', example: 'The airline compensated passengers for the delayed flight.' },
  { id: 18, en: 'competent', ko: '유능한', level: '800', example: 'She is a competent manager with years of experience.' },
  { id: 19, en: 'comply', ko: '준수하다', level: '800', example: 'All staff must comply with the new safety regulations.' },
  { id: 20, en: 'comprehensive', ko: '포괄적인', level: '800', example: 'The report provides a comprehensive analysis of the market.' },
  { id: 21, en: 'conclude', ko: '결론을 내리다, 종료하다', level: '800', example: 'The meeting concluded with a summary of action items.' },
  { id: 22, en: 'confidential', ko: '기밀의', level: '800', example: 'This document contains confidential financial information.' },
  { id: 23, en: 'consecutive', ko: '연속적인', level: '900', example: 'Sales have increased for three consecutive quarters.' },
  { id: 24, en: 'consolidate', ko: '통합하다', level: '900', example: 'The two branches will be consolidated into one office.' },
  { id: 25, en: 'constraint', ko: '제약', level: '900', example: 'Budget constraints delayed the launch of the new product.' },
  { id: 26, en: 'consult', ko: '상담하다, 참고하다', level: '800', example: 'Please consult the manual before installing the software.' },
  { id: 27, en: 'contribute', ko: '기여하다', level: '800', example: "Every team member contributed to the project's success." },
  { id: 28, en: 'convene', ko: '소집하다', level: '900', example: 'The board will convene next Tuesday to discuss the merger.' },
  { id: 29, en: 'corporate', ko: '기업의', level: '800', example: 'The corporate office is located downtown.' },
  { id: 30, en: 'correspond', ko: '일치하다, 서신을 주고받다', level: '800', example: 'The invoice number should correspond to the order number.' },
  { id: 31, en: 'credential', ko: '자격 증명', level: '900', example: 'Applicants must submit their credentials before the interview.' },
  { id: 32, en: 'deduct', ko: '공제하다', level: '800', example: 'Taxes are automatically deducted from your paycheck.' },
  { id: 33, en: 'delegate', ko: '위임하다', level: '800', example: 'The director delegated the task to her assistant.' },
  { id: 34, en: 'deliberate', ko: '신중한', level: '900', example: 'The committee made a deliberate decision after careful review.' },
  { id: 35, en: 'demonstrate', ko: '입증하다, 시연하다', level: '800', example: 'The sales rep demonstrated the new product to the client.' },
  { id: 36, en: 'designate', ko: '지정하다', level: '800', example: 'A conference room has been designated for the interviews.' },
  { id: 37, en: 'discrepancy', ko: '차이, 불일치', level: '900', example: 'There is a discrepancy between the two reports.' },
  { id: 38, en: 'dispatch', ko: '발송하다', level: '900', example: 'The order was dispatched the same day it was placed.' },
  { id: 39, en: 'dispose', ko: '처분하다', level: '900', example: 'The company disposed of outdated equipment.' },
  { id: 40, en: 'distribute', ko: '분배하다, 배포하다', level: '800', example: 'Handouts will be distributed at the beginning of the seminar.' },
  { id: 41, en: 'diverse', ko: '다양한', level: '800', example: 'The company has a diverse workforce from many countries.' },
  { id: 42, en: 'draft', ko: '초안(을 작성하다)', level: '800', example: 'She drafted the proposal before sending it to the client.' },
  { id: 43, en: 'eligible', ko: '자격이 있는', level: '800', example: 'Full-time employees are eligible for health insurance.' },
  { id: 44, en: 'endorse', ko: '지지하다, 보증하다', level: '900', example: 'The manager endorsed the plan without any changes.' },
  { id: 45, en: 'enforce', ko: '시행하다', level: '900', example: 'The new policy will be strictly enforced starting next month.' },
  { id: 46, en: 'enhance', ko: '향상시키다', level: '800', example: "The update will enhance the software's performance." },
  { id: 47, en: 'entail', ko: '수반하다', level: '900', example: 'The new role entails frequent travel.' },
  { id: 48, en: 'establish', ko: '설립하다, 확립하다', level: '800', example: 'The company was established in 1998.' },
  { id: 49, en: 'estimate', ko: '추정하다', level: '800', example: 'The contractor estimated the cost of the renovation.' },
  { id: 50, en: 'evaluate', ko: '평가하다', level: '800', example: 'Supervisors evaluate staff performance twice a year.' },
  { id: 51, en: 'exceed', ko: '초과하다', level: '800', example: 'Sales this quarter exceeded expectations.' },
  { id: 52, en: 'exempt', ko: '면제된', level: '900', example: 'Nonprofit organizations are exempt from certain taxes.' },
  { id: 53, en: 'expand', ko: '확장하다', level: '800', example: 'The firm plans to expand into overseas markets.' },
  { id: 54, en: 'expedite', ko: '신속히 처리하다', level: '900', example: 'We expedited the shipment to meet the deadline.' },
  { id: 55, en: 'facilitate', ko: '촉진하다, 용이하게 하다', level: '800', example: 'The new software facilitates communication between teams.' },
  { id: 56, en: 'feasible', ko: '실현 가능한', level: '800', example: 'The proposed timeline is not feasible given our resources.' },
  { id: 57, en: 'finalize', ko: '마무리하다', level: '800', example: 'We need to finalize the contract by Friday.' },
  { id: 58, en: 'fluctuate', ko: '변동하다', level: '900', example: 'Currency exchange rates fluctuate daily.' },
  { id: 59, en: 'forecast', ko: '예측하다', level: '800', example: 'Analysts forecast steady growth next year.' },
  { id: 60, en: 'fundamental', ko: '근본적인', level: '800', example: 'Customer satisfaction is fundamental to our business.' },
  { id: 61, en: 'implement', ko: '시행하다', level: '800', example: 'The company will implement a new attendance policy.' },
  { id: 62, en: 'incentive', ko: '장려책, 보상', level: '800', example: 'Employees receive incentives for meeting sales targets.' },
  { id: 63, en: 'inevitable', ko: '불가피한', level: '900', example: 'Some delays were inevitable due to the weather.' },
  { id: 64, en: 'initiate', ko: '시작하다', level: '800', example: 'The manager initiated the project last week.' },
  { id: 65, en: 'innovative', ko: '혁신적인', level: '800', example: 'The startup is known for its innovative products.' },
  { id: 66, en: 'inquiry', ko: '문의', level: '800', example: 'Please direct all inquiries to the customer service desk.' },
  { id: 67, en: 'inspect', ko: '점검하다', level: '800', example: 'The factory is inspected regularly for safety compliance.' },
  { id: 68, en: 'instruct', ko: '지시하다', level: '800', example: 'Employees were instructed to submit reports by Monday.' },
  { id: 69, en: 'intact', ko: '손상되지 않은, 온전한', level: '900', example: 'The packages arrived intact despite the rough handling.' },
  { id: 70, en: 'integrate', ko: '통합하다', level: '800', example: 'The two systems were integrated into one platform.' },
  { id: 71, en: 'interfere', ko: '방해하다', level: '900', example: 'Personal matters should not interfere with work.' },
  { id: 72, en: 'inventory', ko: '재고', level: '800', example: 'The store conducts an inventory check every month.' },
  { id: 73, en: 'invoice', ko: '송장, 청구서', level: '800', example: 'The supplier sent an invoice for the recent shipment.' },
  { id: 74, en: 'itinerary', ko: '여행 일정', level: '800', example: 'The travel agent prepared a detailed itinerary for the trip.' },
  { id: 75, en: 'lucrative', ko: '수익성이 좋은', level: '900', example: 'They signed a lucrative contract with an overseas partner.' },
  { id: 76, en: 'mandatory', ko: '의무적인', level: '800', example: 'Attendance at the safety seminar is mandatory.' },
  { id: 77, en: 'merge', ko: '합병하다', level: '800', example: 'The two companies merged to form a larger corporation.' },
  { id: 78, en: 'mitigate', ko: '완화하다', level: '900', example: 'The new policy aims to mitigate financial risks.' },
  { id: 79, en: 'negotiate', ko: '협상하다', level: '800', example: 'Both sides negotiated the terms of the contract.' },
  { id: 80, en: 'notify', ko: '알리다', level: '800', example: 'Please notify the office if you will be late.' },
  { id: 81, en: 'obsolete', ko: '구식의', level: '800', example: 'The old machinery has become obsolete.' },
  { id: 82, en: 'optimize', ko: '최적화하다', level: '800', example: 'The team optimized the workflow to save time.' },
  { id: 83, en: 'outline', ko: '개요(를 서술하다)', level: '800', example: 'The manager outlined the goals for the upcoming quarter.' },
  { id: 84, en: 'overhead', ko: '간접비, 운영비', level: '900', example: "Reducing overhead costs improved the company's profit margin." },
  { id: 85, en: 'permanent', ko: '영구적인, 정규직의', level: '800', example: 'She was offered a permanent position after her internship.' },
  { id: 86, en: 'postpone', ko: '연기하다', level: '800', example: 'The meeting was postponed due to a scheduling conflict.' },
  { id: 87, en: 'proficient', ko: '능숙한', level: '800', example: 'Applicants should be proficient in spreadsheet software.' },
  { id: 88, en: 'prohibit', ko: '금지하다', level: '800', example: 'Smoking is prohibited inside the building.' },
  { id: 89, en: 'prominent', ko: '저명한, 두드러진', level: '900', example: 'She is a prominent figure in the finance industry.' },
  { id: 90, en: 'prompt', ko: '신속한', level: '800', example: 'We appreciate your prompt response to our inquiry.' },
  { id: 91, en: 'proportion', ko: '비율', level: '800', example: 'A large proportion of revenue comes from overseas sales.' },
  { id: 92, en: 'prospective', ko: '잠재적인, 장래의', level: '800', example: 'The company is meeting with several prospective clients.' },
  { id: 93, en: 'provision', ko: '조항, 공급', level: '900', example: 'The contract includes a provision for early termination.' },
  { id: 94, en: 'qualify', ko: '자격을 얻다', level: '800', example: 'Candidates must qualify through a written exam.' },
  { id: 95, en: 'rebate', ko: '환불금, 리베이트', level: '900', example: 'Customers can receive a rebate after registering the product.' },
  { id: 96, en: 'recruit', ko: '모집하다', level: '800', example: 'The company plans to recruit ten new engineers this year.' },
  { id: 97, en: 'redundant', ko: '불필요한, 잉여의', level: '900', example: 'Several positions were made redundant after the merger.' },
  { id: 98, en: 'refund', ko: '환불(하다)', level: '800', example: 'The store offers a full refund within 30 days.' },
  { id: 99, en: 'regulate', ko: '규제하다', level: '800', example: 'The industry is closely regulated by the government.' },
  { id: 100, en: 'reimburse', ko: '상환하다, 환급하다', level: '800', example: 'The company will reimburse employees for travel expenses.' },
]
