// 중국어 단어장 HSK 3~4급 수준 어휘 (Day 1~100, 하루 30개)
// 각 항목: { id, hanzi(한자), pinyin(성조 포함, 한자 1글자당 음절 1개씩 공백 구분), ko(뜻), day }
const WORDS = [
  { id: 1, hanzi: '学习', pinyin: 'xué xí', ko: '공부하다, 배우다', day: 1 },
  { id: 2, hanzi: '工作', pinyin: 'gōng zuò', ko: '일, 일하다', day: 1 },
  { id: 3, hanzi: '经验', pinyin: 'jīng yàn', ko: '경험', day: 1 },
  { id: 4, hanzi: '环境', pinyin: 'huán jìng', ko: '환경', day: 1 },
  { id: 5, hanzi: '社会', pinyin: 'shè huì', ko: '사회', day: 1 },
  { id: 6, hanzi: '关系', pinyin: 'guān xì', ko: '관계', day: 1 },
  { id: 7, hanzi: '机会', pinyin: 'jī huì', ko: '기회', day: 1 },
  { id: 8, hanzi: '计划', pinyin: 'jì huà', ko: '계획, 계획하다', day: 1 },
  { id: 9, hanzi: '决定', pinyin: 'jué dìng', ko: '결정하다', day: 1 },
  { id: 10, hanzi: '解决', pinyin: 'jiě jué', ko: '해결하다', day: 1 },
  { id: 11, hanzi: '发展', pinyin: 'fā zhǎn', ko: '발전하다', day: 1 },
  { id: 12, hanzi: '提高', pinyin: 'tí gāo', ko: '향상시키다, 높이다', day: 1 },
  { id: 13, hanzi: '影响', pinyin: 'yǐng xiǎng', ko: '영향, 영향을 주다', day: 1 },
  { id: 14, hanzi: '改变', pinyin: 'gǎi biàn', ko: '바꾸다, 변화하다', day: 1 },
  { id: 15, hanzi: '表示', pinyin: 'biǎo shì', ko: '나타내다, 표시하다', day: 1 },
  { id: 16, hanzi: '认为', pinyin: 'rèn wéi', ko: '~라고 여기다, 생각하다', day: 1 },
  { id: 17, hanzi: '感觉', pinyin: 'gǎn jué', ko: '느끼다, 느낌', day: 1 },
  { id: 18, hanzi: '需要', pinyin: 'xū yào', ko: '필요하다', day: 1 },
  { id: 19, hanzi: '希望', pinyin: 'xī wàng', ko: '희망하다, 바라다', day: 1 },
  { id: 20, hanzi: '提供', pinyin: 'tí gōng', ko: '제공하다', day: 1 },
  { id: 21, hanzi: '参加', pinyin: 'cān jiā', ko: '참가하다', day: 1 },
  { id: 22, hanzi: '准备', pinyin: 'zhǔn bèi', ko: '준비하다', day: 1 },
  { id: 23, hanzi: '完成', pinyin: 'wán chéng', ko: '완성하다', day: 1 },
  { id: 24, hanzi: '继续', pinyin: 'jì xù', ko: '계속하다', day: 1 },
  { id: 25, hanzi: '发现', pinyin: 'fā xiàn', ko: '발견하다', day: 1 },
  { id: 26, hanzi: '了解', pinyin: 'liǎo jiě', ko: '이해하다, 알다', day: 1 },
  { id: 27, hanzi: '增加', pinyin: 'zēng jiā', ko: '증가하다', day: 1 },
  { id: 28, hanzi: '减少', pinyin: 'jiǎn shǎo', ko: '감소하다', day: 1 },
  { id: 29, hanzi: '联系', pinyin: 'lián xì', ko: '연락하다', day: 1 },
  { id: 30, hanzi: '适应', pinyin: 'shì yìng', ko: '적응하다', day: 1 },
];
